config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  devise_for :users

  resources :tasks do
    member do
      patch :complete
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  def completed?
    !self.completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy, :complete]
  before_action :authenticate_user!, except: [:index, :show, :edit, :update, :destroy]

  def index
    @tasks = current_user.tasks.order("created_at DESC") if user_signed_in?
  end

  def show
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to @task, notice: "Task successfully created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect @task, notice: "Task successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path, notice: "Task deleted!"
  end

  def complete
    if @task.completed?
      @task.update_attribute(:completed_at, nil)
      redirect_to root_path, notice: "Task successfully updated!"
    else
      @task.update_attribute(:completed_at, Time.now)
      redirect_to root_path, notice: "Task completed!"
    end
  end

  private

    def task_params
      params.require(:task).permit(:title, :description)
    end

    def find_task
      @task = current_user.tasks.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Hiptime
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", "content" => "width=device-width, initial-scale=1, shrink-to-fit=no"}

    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
      .container
        = link_to "Hiptime", root_path, class: "navbar-brand"

        %button.navbar-toggler{:type => "button", "data-toggle" => "collapse", "data-target" => "#navbarNavAltMarkup", "aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation"}
          %span.navbar-toggler-icon
        #navbarNavAltMarkup.collapse.navbar-collapse
          .navbar-nav.ml-auto
            - if user_signed_in?
              = link_to "New Task", new_task_path, class: "nav-item nav-link"
              = link_to "Edit User", edit_user_registration_path, class: "nav-item nav-link"
              = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link"

            -else
              = link_to "Join", new_user_registration_path, class: "nav-item nav-link"
              = link_to "Log In", new_user_session_path, class: "nav-item nav-link"

    .container.my-4
      - unless flash.empty?
        - flash.each do |name, msg|
          = content_tag :div, msg, class: "alert alert-info"
        %hr.mb-4

      = yield

app/views/tasks/_form.html.haml
= simple_form_for @task do |f|
  = f.input :title
  = f.input :description
  = f.button :submit

app/views/tasks/_welcome.html.haml
.jumbotron
  .container
    %h1.display-3 HipTime! Free and Easy.
    %p.lead Trusted by Millions. HipTime is the best online Task Management App!
    %hr.my-4
    .row.justify-content-center
      = link_to "Try it Now!", new_user_registration_path, class: "btn btn-primary"

app/views/tasks/edit.html.haml
.col-md-8.mx-auto
  %h1 Edit ToDo Item

  = render "form"

app/views/tasks/index.html.haml
- if user_signed_in?
  - @tasks.each do |task|
    - if task.completed?
      .row
        .col-md-1
          = link_to complete_task_path(task), method: :patch do
            = fa_icon "check-square-o 2x"

        .col-md-1
          = link_to task, method: :delete, data: { confirm: "Are you sure?" } do
            = fa_icon "trash-o 2x"

        .col-md-10
          %h2.opacity-05
            %strike
              = link_to task.title, task
          %p.text-justify.opacity-05= task.description
          %p.lead.opacity-05
            %small
              Completed
              = time_ago_in_words(task.completed_at)
              ago

    - else
      .row
        .col-md-1
          = link_to complete_task_path(task), method: :patch do
            = fa_icon "square-o 2x"

        .col-md-10
          %h2= link_to task.title, task
          %p.text-justify= task.description
          %p.lead
            %small
              Created
              = time_ago_in_words(task.created_at)
              ago

        .col-md-1
          = link_to task, method: :delete, data: { confirm: "Are you sure?" } do
            = fa_icon "trash-o 2x"

- else
  = render "welcome"

app/views/tasks/new.html.haml
.col-md-8.mx-auto
  %h1 New ToDo Item

  = render "form"

app/views/tasks/show.html.haml
.col-md-10.mx-auto
  %h2= @task.title
  %p= @task.description

  .col-md-4.mx-auto
    = link_to "Back", root_path
    = link_to "Edit", edit_task_path(@task)
    = link_to "Delete", task_path(@task), method: :delete, data: { confirm: "Are you sure?" }